### ISSUE TITLE
ARM Support?

### ISSUE THREAD

**Issue by samoht9277** [LGUG2Z/nixos-hetzner-robot-starter#1]
This nix project seems pretty good, but it doesnt seem to work on my scenario.

I'm running a MacBook Air M2 (`aarch64-darwin`).

I need to set up an `AX102` server, which has a Ryzen 9 (`x86_64-linux`).

The nix command on my machine fails, with the following output:
```sh
~/nixos-hetzner-robot-starter master 
❯ nix run github:numtide/nixos-anywhere -- --flake .#robot root@<MY_IP>
warning: unknown setting 'upgrade-nix-store-path-url'
warning: Git tree '/Users/tomi/nixos-hetzner-robot-starter' is dirty
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
error: a 'x86_64-linux' with features {} is required to build '/nix/store/8kqwgc61lhpwa86fib2ha7cjw0p60kmh-disko.drv', but I am a 'aarch64-darwin' with features {apple-virt, benchmark, big-parallel, nixos-test}
```

**Comment by jamesbirtles** [comment]
Theres a `--build-on-remote` flag you can append to the command that lets things run, though I've yet to get a server to boot properly with this setup

**Comment by LGUG2Z** [comment]
This is more of a general Nix question rather than specific to this repo, but if you want to cross compile packages from aarch64 to x86 on an ARM Mac you'll need to configure this: https://daiderd.com/nix-darwin/manual/index.html#opt-nix.linux-builder.enable

There is an example in my corp starter that you can use as a starting point: https://github.com/LGUG2Z/nix-home-manager-corp-starter/blob/85ceb5772fcee1ae8b526ad6b2036f9d7ba4aab7/modules/darwin.nix#L25
